spring.application.name=travelplanner
spring.profiles.active=stage

server.port=8082

# \u2500\u2500\u2500 Database \u2500\u2500\u2500
spring.datasource.url=jdbc:mysql://localhost:3306/travelplanner
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# \u2500\u2500\u2500 Disable open-in-view warning \u2500\u2500\u2500
spring.jpa.open-in-view=false

# \u2500\u2500\u2500 Gmail SMTP \u2500\u2500\u2500
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shravanibhalerao26@gmail.com
spring.mail.password=jvofiqhvxnizvnip

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000